### ISSUE TITLE
MacOS not working?

### ISSUE THREAD

**Issue by marcel-bluestone** [loicmagne/air-drawing#3]
Hi, I tried air-drawing on a MacBook Pro 13 M1 however it seems that neither pose is recognized. The lighting should be ok.
Could it be, that the webcam is not good enough to detect the hand pose?
Did anyone test this on a MacBook already?

**Comment by loicmagne** [comment]
I haven't tried it on macbook, but even with a bad webcam it should still make some rough handpose prediction, so I'd say it's a compatibility issue. Do you have any error message in the console (right click -> inspect -> console) when you load the page ?

**Comment by marcel-bluestone** [comment]
Ha, this shows an error. It seems that mediapipe is not available for the M1 yet.
Thanks for pointing me to the right direction.
